[workspace]
resolver = "3"
members = [
   "types",
   "lookup",
   "position",
   "engine",
   "uci",
   "bench"
]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
debug = 0
incremental = false
overflow-checks = false

[profile.profiling]
inherits = "release"
debug = 1
strip = false
force-frame-pointers = true
